import { MigrationInterface, QueryRunner } from "typeorm";

export class AutoGeneratedMigrations1704439683108 implements MigrationInterface {
    name = 'AutoGeneratedMigrations1704439683108'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "UserRecipes" ("recipeId" integer NOT NULL, "userId" integer NOT NULL, CONSTRAINT "PK_be838f0dc4be049a11db06eb1ff" PRIMARY KEY ("recipeId", "userId"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "UserRecipes"`);
    }

}
